config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :dashboard
  post 'dashboard' => 'dashboard#render_product_partial_form'

  resources :products_services

  delete 'customer_product/:id(.:format)' => 'products_services#destroy_customer_product', as: 'destroy_customer_product'
  delete 'customer_service/:id(.:format)' => 'products_services#destroy_customer_service', as: 'destroy_customer_service'

  get 'customer_product/:id(.:format)' => 'products_services#edit_customer_product', as: 'edit_customer_product'
  get 'customer_service/:id(.:format)' => 'products_services#edit_customer_service', as: 'edit_customer_service'

  post 'customer_product/:id(.:format)' => 'products_services#update_customer_product', as: 'update_customer_product'
  post 'customer_service/:id(.:format)' => 'products_services#update_customer_service', as: 'update_customer_service'

  resources :customers
  post 'customers/:id/' => 'customers#show_range', as: 'customer_range'

  resources :expenses

  resources :services do
    member do
      patch :toggle_enabled
    end
  end

  resources :products do
    member do
      patch :toggle_enabled
    end
  end

  resources :partners do
    member do
      patch :toggle_enabled
    end
  end

  resources :discounts do
    member do
      patch :toggle_enabled
    end
  end
  #path for charts
  get 'customer/products_services_by_day/:id/:range(.:format)' => 'customers#products_services_by_day', as: "customer_products_services_by_day"
  get 'dashboard_index/products_services_by_day' => 'dashboard#products_services_by_day', as: "dashboard_products_services_by_day"
  get 'dashboard_index/customers_by_sex' => 'dashboard#customers_by_sex', as: "dashboard_customers_by_sex"
  get 'dashboard_index/by_service' => 'dashboard#by_service', as: "dashboard_by_service"
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :customer_services, :dependent => :restrict_with_error
  has_many :customers, through: :customer_services, :dependent => :restrict_with_error
  scope :by_user, ->(current_user) {where(user: current_user).order(name: :desc)}
  before_save :price_validation

  def create_with_user(current_user)
    self.user = current_user if user.nil?
    save
  end

  def price_in_euro
    "#{price}€"
  end

  def to_s
    [name, description, price_in_euro].reject(&:blank?).join(" - ")
  end

  def to_s_name_description
    [name, description].reject(&:blank?).join(" - ")
  end

  def price_validation
    if price.blank?
      self.price = 0
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @records = Service.by_user(current_user)
  end

  def create
    Service.new(service_params).create_with_user(current_user)
    redirect_to services_path
  end

  def edit
    @records = Service.by_user(current_user)
    @record = Service.by_user(current_user).find(params[:id])
  end

  def update
    @record = Service.by_user(current_user).find(params[:id])
    if @record.update_attributes(service_params)
      redirect_to services_path
    else
      render 'edit'
    end
  end

  def destroy
    @record = Service.by_user(current_user).find(params[:id])
    @record.destroy
    redirect_to services_path
  end

  def toggle_enabled
    @record = Service.by_user(current_user).find(params[:id])
    @record.toggle!(:enabled)
    redirect_to services_path
  end

  def service_params
    params.require(:service).permit(:name, :description, :enabled, :price)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_create_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Δημιουργία Υπηρεσίας</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <%= bootstrap_form_for :service, url: {controller: 'services', action: 'create'} do |f| %>
      <%= f.text_field :name, label: 'Όνομα' %>
      <%= f.text_area :description, label: 'Περιγραφή' %>
      <%= f.number_field :price, label: 'Τιμή',
                         class: :text_field,
                         step: :any %>
      <%= f.check_box :enabled, {label: 'Ενεργός', checked: true} %>

      <%= f.form_group do %>
        <%= f.primary 'Δημιουργία' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/services/_edit_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Ενημέρωση Υπηρεσίας</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <%= bootstrap_form_for @record, url: {controller: 'services', action: 'update'} do |f| %>
      <%= f.text_field :name, label: 'Όνομα' %>
      <%= f.text_area :description, label: 'Περιγραφή' %>
      <%= f.number_field :price, label: 'Τιμή',
                         class: :text_field,
                         step: :any %>
      <%= f.check_box :enabled, {label: 'Ενεργός'} %>

      <%= f.form_group do %>
        <%= f.primary 'Ενημέρωση' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/services/_table.erb
<div class="x_panel">
  <div class="x_content">
    <table id="datatable-services" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>Όνομα</th>
        <th>Περιγραφή</th>
        <th>Τιμή</th>
        <th>Ενεργος</th>
        <th>Ενημέρωση</th>
        <th>Διαγραφή</th>
      </tr>
      </thead>
      <tbody>
      <% @records.each {|record| %>
        <tr>
          <%= row(record.name) %>
          <%= row(record.description) %>
          <%= row(record.price_in_euro) %>
          <%= enabled_row(toggle_enabled_service_path(record), record.enabled) %>
          <%= edit_row(edit_service_path(record)) %>
          <%= delete_row(record) %>
        </tr>
      <% } %>
      </tbody>
    </table>
  </div>
</div>

<script>
    $('#datatable-services').DataTable({
        "columnDefs": [
            {"width": "50px", "targets": [3, 4, 5], "orderable": false, "className": "text-center"}
        ],
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Greek.json"
        }
    });
</script>

app/views/services/edit.html.erb
<div class="col-md-8 col-sm-8 col-xs-12">
  <%= render 'services/table' %>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
  <%= render 'services/edit_form' %>
</div>

app/views/services/index.html.erb
<div class="col-md-8 col-sm-8 col-xs-12">
  <%= render 'services/table' %>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
  <%= render 'services/create_form' %>
</div>