config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :dashboard
  post 'dashboard' => 'dashboard#render_product_partial_form'

  resources :products_services

  delete 'customer_product/:id(.:format)' => 'products_services#destroy_customer_product', as: 'destroy_customer_product'
  delete 'customer_service/:id(.:format)' => 'products_services#destroy_customer_service', as: 'destroy_customer_service'

  get 'customer_product/:id(.:format)' => 'products_services#edit_customer_product', as: 'edit_customer_product'
  get 'customer_service/:id(.:format)' => 'products_services#edit_customer_service', as: 'edit_customer_service'

  post 'customer_product/:id(.:format)' => 'products_services#update_customer_product', as: 'update_customer_product'
  post 'customer_service/:id(.:format)' => 'products_services#update_customer_service', as: 'update_customer_service'

  resources :customers
  post 'customers/:id/' => 'customers#show_range', as: 'customer_range'

  resources :expenses

  resources :services do
    member do
      patch :toggle_enabled
    end
  end

  resources :products do
    member do
      patch :toggle_enabled
    end
  end

  resources :partners do
    member do
      patch :toggle_enabled
    end
  end

  resources :discounts do
    member do
      patch :toggle_enabled
    end
  end
  #path for charts
  get 'customer/products_services_by_day/:id/:range(.:format)' => 'customers#products_services_by_day', as: "customer_products_services_by_day"
  get 'dashboard_index/products_services_by_day' => 'dashboard#products_services_by_day', as: "dashboard_products_services_by_day"
  get 'dashboard_index/customers_by_sex' => 'dashboard#customers_by_sex', as: "dashboard_customers_by_sex"
  get 'dashboard_index/by_service' => 'dashboard#by_service', as: "dashboard_by_service"
end

app/views/layouts/shared/_footer.html.erb
<footer>
<div class="pull-right">
   <a href="http://orbitsystems.gr">Orbit Systems</a>
</div>
<div class="clearfix"></div>
</footer>

app/views/layouts/shared/_leftnav.html.erb
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="/" class="site_title">
        <%= image_tag :hair_flair, class: 'img-horizontal site_img' %>
      </a>
    </div>


    <div class="navbar profile">
      <div class="profile_pic">
        <%= image_tag(current_user.avatar.url(:medium), class: "img-circle profile_img") %>
      </div>
      <div class="profile_info">
        <span>Καλωσόρισες,</span>
        <h2><%= current_user.username %></h2>
      </div>
    </div>
    <!-- /menu profile quick info -->

    <br/>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <ul class="nav side-menu">
          <li>   <%= link_to('Αρχική σελίδα', "/") %></li>
          <li>   <%= link_to('Πελάτες', customers_path) %></li>
          <li>  <%= link_to('Υπηρεσίες', services_path) %></li>
          <li>   <%= link_to('Προϊόντα', products_path) %></li>
          <li>   <%= link_to('Συνεργάτες', partners_path) %></li>
          <li>   <%= link_to('Έξοδα', expenses_path) %></li>
          <li>   <%= link_to('Εκπτώσεις', discounts_path) %></li>
        </ul>
      </div>
    </div>
    <!-- /sidebar menu -->
    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
      <%= link_to edit_user_registration_path, :'data-placement' => 'top', :'title' => 'Ρυθμίσεις', :'data-toggle' => 'tooltip' do %>
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      <% end %>

      <%= link_to destroy_user_session_path, method: :delete, :'data-placement' => 'top', :'title' => 'Αποσύνδεση', :'data-toggle' => 'tooltip' do %>
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/shared/_topnav.html.erb
<div class="top_nav top_nav_fixed">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        <a id="tiles_toggle"><i class="glyphicon glyphicon-chevron-down" id="tiles_toggle_icon"></i></a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag(current_user.avatar.url(:medium)) %>

            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><%= link_to('Προφίλ', edit_user_registration_path) %></li>
            <li><%= link_to('Αποσύνδεση', destroy_user_session_path, method: :delete) %></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>