config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :dashboard
  post 'dashboard' => 'dashboard#render_product_partial_form'

  resources :products_services

  delete 'customer_product/:id(.:format)' => 'products_services#destroy_customer_product', as: 'destroy_customer_product'
  delete 'customer_service/:id(.:format)' => 'products_services#destroy_customer_service', as: 'destroy_customer_service'

  get 'customer_product/:id(.:format)' => 'products_services#edit_customer_product', as: 'edit_customer_product'
  get 'customer_service/:id(.:format)' => 'products_services#edit_customer_service', as: 'edit_customer_service'

  post 'customer_product/:id(.:format)' => 'products_services#update_customer_product', as: 'update_customer_product'
  post 'customer_service/:id(.:format)' => 'products_services#update_customer_service', as: 'update_customer_service'

  resources :customers
  post 'customers/:id/' => 'customers#show_range', as: 'customer_range'

  resources :expenses

  resources :services do
    member do
      patch :toggle_enabled
    end
  end

  resources :products do
    member do
      patch :toggle_enabled
    end
  end

  resources :partners do
    member do
      patch :toggle_enabled
    end
  end

  resources :discounts do
    member do
      patch :toggle_enabled
    end
  end
  #path for charts
  get 'customer/products_services_by_day/:id/:range(.:format)' => 'customers#products_services_by_day', as: "customer_products_services_by_day"
  get 'dashboard_index/products_services_by_day' => 'dashboard#products_services_by_day', as: "dashboard_products_services_by_day"
  get 'dashboard_index/customers_by_sex' => 'dashboard#customers_by_sex', as: "dashboard_customers_by_sex"
  get 'dashboard_index/by_service' => 'dashboard#by_service', as: "dashboard_by_service"
end

app/controllers/products_services_controller.rb
# noinspection RailsChecklist01
class ProductsServicesController < ApplicationController

  def create
    customer_id = p_params[:customer_id]
    unless customer_id.nil?
      date = p_params[:created_at]
      partner_id = p_params[:partner_id]
      discount_id = p_params[:discount_id]
      discount_per_cent = p_params[:discount_per_cent]

      if discount_per_cent.blank?
        discount_per_cent = 0
      end
      discount_per_cent = Integer(discount_per_cent)

      unless p_params['customer_products'].nil?
        p_params['customer_products'].each do |record_params|
          unless record_params[:product_id].blank?
            price = Integer(Product.by_user(current_user).find(record_params[:product_id]).price)
            extra_params = {customer_id: customer_id,
                            partner_id: partner_id,
                            date: date,
                            discount_id: discount_id,
                            discount_per_cent: discount_per_cent,
                            price: price}
            save_product_or_service(CustomerProduct.new(record_params), extra_params)
          end
        end
      end
      unless p_params['customer_services'].nil?
        p_params['customer_services'].each do |record_params|
          unless record_params[:service_id].blank?
            price = Integer(Service.by_user(current_user).find(record_params[:service_id]).price)
            extra_params = {customer_id: customer_id,
                            partner_id: partner_id,
                            date: date,
                            discount_id: discount_id,
                            discount_per_cent: discount_per_cent,
                            price: price}
            save_product_or_service(CustomerService.new(record_params), extra_params)
          end
        end
      end
    end
    redirect_to dashboard_index_path
  end


  def destroy_customer_product
    @record = CustomerProduct.by_user(current_user).find(params[:id]).destroy
    redirect_to dashboard_index_path
  end

  def destroy_customer_service
    @record = CustomerService.by_user(current_user).find(params[:id]).destroy
    redirect_to dashboard_index_path
  end

  def edit_customer_product
    @customers = Customer.by_user(current_user)
    @records = Product.by_user(current_user).where(enabled: true)
    @partners = Partner.by_user(current_user).where(enabled: true)
    @discounts = Discount.by_user(current_user).where(enabled: true)
    @record = CustomerProduct.by_user(current_user).find(params[:id])
  end

  def edit_customer_service
    @customers = Customer.by_user(current_user)
    @records = Service.by_user(current_user).where(enabled: true)
    @partners = Partner.by_user(current_user).where(enabled: true)
    @discounts = Discount.by_user(current_user).where(enabled: true)
    @record = CustomerService.by_user(current_user).find(params[:id])
  end

  def update_customer_product
    @record = CustomerProduct.by_user(current_user).find(params[:id])

    if update_product_or_service(@record, product_params, @record.product.price)
      redirect_to dashboard_index_path
    else
      render 'edit_customer_product'
    end
  end

  def update_customer_service
    @record = CustomerService.by_user(current_user).find(params[:id])
    if update_product_or_service(@record, service_params, @record.service.price)
      redirect_to dashboard_index_path
    else
      render 'edit_customer_service'
    end
  end

  def save_product_or_service(record, extra)
    unless extra[:date].blank?
      record.created_at = extra[:date]
    end

    unless extra[:discount_id].blank?
      record.discount_id = extra[:discount_id]
    end

    record.discount_per_cent = extra[:discount_per_cent]

    if record.partner_id.blank?
      record.partner_id = extra[:partner_id]
    end

    if record.price.blank?
      record.price = extra[:price]
    end
    record.price = ((100 - extra[:discount_per_cent]) * record.price / 100).round(2)

    if record.amount.blank?
      record.amount = 1
    end
    record.customer_id = extra[:customer_id]
    record.create_with_user(current_user)
  end

  def update_product_or_service(record, parameters, default_price)
    discount_per_cent = parameters[:discount_per_cent]
    price = parameters[:price]
    discount_per_cent.nil? ? discount_per_cent = 0.0 : discount_per_cent = Float(discount_per_cent)
    price.nil? ? price = default_price : price = Float(price)

    parameters[:discount_per_cent] = discount_per_cent
    parameters[:price] = ((100 - discount_per_cent) * price / 100).round(2)
    record.update_attributes(parameters)
  end

  def p_params
    params.permit(:customer_id, :partner_id, :created_at, :discount_id, :discount_per_cent,
                  {:customer_products => [:product_id, :partner_id, :amount, :price, :comment, :created_at]},
                  {:customer_services => [:service_id, :partner_id, :amount, :price, :comment, :created_at]})
  end

  def product_params
    params.require(:customer_product).permit(:customer_id, :partner_id, :discount_id, :discount_per_cent, :product_id, :amount, :price, :comment, :created_at)
  end

  def service_params
    params.require(:customer_service).permit(:customer_id, :partner_id, :discount_id, :discount_per_cent, :service_id, :amount, :price, :comment, :created_at)
  end
end

app/helpers/products_services_helper.rb
module ProductsServicesHelper
end

app/views/products_services/_create_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2 id="dd">Προσθήκη Υπηρεσιών και Προϊόντων</h2>
    <ul class='nav navbar-right panel_toolbox'>
      <h2 class="green sum">0€</h2>

      <li><a class='collapse-link'><i class='fa fa-chevron-up'></i></a>
      </li>
    </ul>
    <div class="clearfix"></div>
  </div>
  <div class="x_content" style='display: none;'>

    <%= bootstrap_form_tag url: products_services_path, html: {id: 'add_product_service_form'} do |form| %>
      <%= form.select(:customer_id, @customers.pluck(:name, :id),
                      {label: 'Επιλέξτε Πελάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                      {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
      <%= form.select(:partner_id, @partners.pluck(:name, :id),
                      {label: 'Επιλέξτε Συνεργάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                      {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
      <div class="col-sm-9">
        <%= form.select(:discount_id, @discounts.collect {|p| [p, p.id, data: {'percent': p.per_cent}]},
                        {label: 'Επιλέξτε Έκπτωση', :prompt => 'Δεν έχει επιλεγεί κάποια'},
                        {class: 'selectpicker', 'data-live-search' => 'true'}) %>
      </div>

      <%= form.number_field :discount_per_cent, label: 'Έκπτωση',
                            data: {toggle: 'tooltip'},
                            min: '0', max: '100',
                            wrapper: {class: 'col-sm-3'} %>


      <%= datepicker_input(form, :created_at) %>

      <hr>
      <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel">
          <a class="panel-heading collapsed" role="tab" id="headingTwo" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            <div id="add_service" class="col-sm-1 navbar-right">
              <div class="round round-sm hollow blue">
                <span class="glyphicon glyphicon-plus"></span>
              </div>
            </div>
            <h4 class="panel-title">Υπηρεσίες</h4>
          </a>
          <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" aria-expanded="false" style="height: 0px;">
            <div class="panel-body">
              <div id="new_services"></div>
            </div>
          </div>
        </div>
        <div class="panel">
          <a class="panel-heading collapsed" role="tab" id="headingOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            <div id="add_product" class="col-sm-1 navbar-right">
              <div class="round round-sm hollow blue">
                <span class="glyphicon glyphicon-plus"></span>
              </div>
            </div>
            <h4 class="panel-title">Προϊόντα</h4>
          </a>
          <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" aria-expanded="false" style="height: 0px;">
            <div class="panel-body">
              <div id="new_products"></div>
            </div>
          </div>
        </div>
      </div>


      <script>
          $('#add_product').click(function () {
              $('#new_products').append("<%= escape_javascript (render partial: 'products_services/product_form', locals: {form: form} ,remote: true) %>");
          });
          $('#add_service').click(function () {
              $('#new_services').append("<%= escape_javascript (render partial: 'products_services/service_form', locals: {form: form} ) %>");
          });
      </script>

      <%= form.form_group do %>
        <%= form.primary 'Προσθήκη' %>
        <h2 class="pull-right green sum">0€</h2>
      <% end %>
      </div>

    <% end %>
    </div>

app/views/products_services/_product_form.html.erb
<div class="panel-body">
  <%= form.fields_for 'customer_products[]', CustomerProduct.new do |c| %>
    <a class="more_fields_toggle pull-right"><i class="glyphicon glyphicon-chevron-down"></i></a>
    <%= c.select(:product_id, @products.collect {|p| [p, p.id, data: {'price': p.price}]},
                 {label: 'Επιλέξτε Προϊόν', :prompt => 'Δεν έχει επιλεγεί κάποιο'},
                 {class: 'selectpicker in_price', 'data-live-search' => 'true'}) %>

    <div class="more_fields" style="display: none;">
      <%= c.select(:partner_id, @partners.pluck(:name, :id),
                   {label: 'Επιλέξτε Συνεργάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                   {class: 'selectpicker form-control', 'data-live-search' => 'true'}) %>
      <%= c.number_field :amount, label: 'Ποσότητα',
                         class: :amount,
                         data: {toggle: 'tooltip'},
                         title: 'αφήστε κενό για ποσότητα ίση με ένα',
                         wrapper: {class: 'col-sm-6'} %>
      <%= c.number_field :price, label: 'Τιμή',
                         class: 'text_field custom_price',
                         step: :'0.01',
                         data: {toggle: 'tooltip'},
                         title: 'αφήστε κενό για την προκαθορισμένη τιμή',
                         wrapper: {class: 'col-sm-6'} %>
      <%= c.text_field :comment, label: 'Σχόλιο' %>
    </div>
  <% end %>
</div>

app/views/products_services/_products_table.html.erb
<%= x_panel 'Προϊόντα', '', true do %>
  <table id="datatable-customer_products" data-turbolinks='false' class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
    <tr>
      <th>Όνομα</th>
      <th>Προϊόν</th>
      <th>Συνεργάτης</th>
      <th>Ποσότητα - Τιμή</th>
      <th>Έκπτωση</th>
      <th>Σχόλιο</th>
      <th>Ημ/Ώρα</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @customer_products.each {|record| %>
      <tr>
        <%= show_row(record.customer, record.customer.name) %>
        <%= row(record.product.to_s_name_description) %>
        <%= row(record.partner.to_s) %>
        <%= row_with_tooltip(record.amount_price,
                             record.price_tooltip,
                             "data-sort='#{record.total_paid}'") %>
        <%= row(record.discount_to_s) %>
        <%= row(record.comment) %>
        <%= row_with_tooltip(record.created_at_s,
                             time_ago_in_words(record.created_at),
                             "data-sort='#{record.created_at}'") %>
        <%= edit_row(edit_customer_product_path(record)) %>
        <%= delete_row(destroy_customer_product_path(record)) %>
      </tr>
    <% } %>
    </tbody>
  </table>
<% end %>

app/views/products_services/_service_form.html.erb
<div class="panel-body">
  <%= form.fields_for 'customer_services[]', CustomerService.new do |c| %>
    <a class="more_fields_toggle pull-right"><i class="glyphicon glyphicon-chevron-down"></i></a>
    <%= c.select(:service_id, @services.collect {|p| [p, p.id, data: {'price': p.price}]},
                 {label: 'Επιλέξτε Υπηρεσία', :prompt => 'Δεν έχει επιλεγεί κάποια'},
                 {class: 'selectpicker in_price', 'data-live-search' => 'true'}) %>

    <div class="more_fields" style="display: none;">
      <%= c.select(:partner_id, @partners.pluck(:name, :id),
                   {label: 'Επιλέξτε Συνεργάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                   {class: 'selectpicker form-control', 'data-live-search' => 'true'}) %>
      <%= c.number_field :amount, label: 'Ποσότητα',
                         class: :amount,
                         data: {toggle: 'tooltip'},
                         title: 'αφήστε κενό για ποσότητα ίση με ένα',
                         wrapper: {class: 'col-sm-6'} %>
      <%= c.number_field :price, label: 'Τιμή',
                         class: 'text_field custom_price',
                         step: :any,
                         data: {toggle: 'tooltip'},
                         title: 'αφήστε κενό για την προκαθορισμένη τιμή',
                         wrapper: {class: 'col-sm-6'} %>
      <%= c.text_field :comment, label: 'Σχόλιο' %>
    </div>

  <% end %>
</div>

app/views/products_services/_services_table.html.erb
<%= x_panel 'Υπηρεσίες', '', true do %>
  <table id="datatable-customer_services" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
    <tr>
      <th>Όνομα</th>
      <th>Υπηρεσία</th>
      <th>Συνεργάτης</th>
      <th>Ποσότητα - Τιμή</th>
      <th>Έκπτωση</th>
      <th>Σχόλιο</th>
      <th>Ημ/Ώρα</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @customer_services.each {|record| %>
      <tr>
        <%= show_row(record.customer, record.customer.name) %>
        <%= row(record.service.to_s_name_description) %>
        <%= row(record.partner.to_s) %>
        <%= row_with_tooltip(record.amount_price,
                             record.price_tooltip,
                             "data-sort='#{record.total_paid}'") %>
        <%= row(record.discount_to_s) %>
        <%= row(record.comment) %>
        <%= row_with_tooltip(record.created_at_s,
                             time_ago_in_words(record.created_at),
                             "data-sort='#{record.created_at}'") %>
        <%= edit_row(edit_customer_service_path(record)) %>
        <%= delete_row(destroy_customer_service_path(record)) %>
      </tr>
    <% } %>
    </tbody>
  </table>
<% end %>

app/views/products_services/edit_customer_product.html.erb
<div class="col-md-4 col-sm-4 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2 id="dd">Ενημέρωση Προϊόντoς</h2>
      <h2 class="pull-right green sum">0€</h2>

      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <div class="panel-body">
        <%= bootstrap_form_tag url: {controller: 'products_services', action: 'update_customer_product'}, html: {id: 'add_product_service_form'} do |form| %>
          <%= form.fields_for @record, url: {controller: 'dashboard', action: 'update_customer_product'} do |f| %>
            <%= f.select(:customer_id, @customers.pluck(:name, :id),
                         {label: 'Επιλέξτε Πελάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                         {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
            <%= f.select(:partner_id, @partners.pluck(:name, :id),
                         {label: 'Επιλέξτε Συνεργάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                         {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
            <%= f.select(:product_id, @records.collect {|p| [p, p.id, data: {'price': p.price}]},
                         {label: 'Επιλέξτε Προϊόν', :prompt => 'Δεν έχει επιλεγεί κάποιο'},
                         {class: 'selectpicker in_price', 'data-live-search' => 'true'}) %>
            <%= datepicker_input(f, :created_at) %>

            <div class="col-sm-9">
              <%= f.select(:discount_id, @discounts.collect {|p| [p, p.id, data: {'percent': p.per_cent}]},
                           {label: 'Επιλέξτε Έκπτωση', :prompt => 'Δεν έχει επιλεγεί κάποια'},
                           {id: 'discount_id', class: 'selectpicker', 'data-live-search' => 'true'}) %>
            </div>

            <%= f.number_field :discount_per_cent, label: 'Έκπτωση',
                               id: 'discount_per_cent',
                               data: {toggle: 'tooltip'},
                               min: '0', max: '100',
                               wrapper: {class: 'col-sm-3'} %>

            <%= f.number_field :amount, label: 'Ποσότητα',
                               class: :amount,
                               data: {toggle: 'tooltip'},
                               title: 'αφήστε κενό για ποσότητα ίση με ένα',
                               wrapper: {class: 'col-sm-6'} %>

            <%= f.number_field :price, label: 'Τιμή',
                               class: 'text_field custom_price',
                               step: :any,
                               value: (@record.price * 100 / (100 - @record.discount_per_cent)).round(2),
                               data: {toggle: 'tooltip'},
                               title: 'αφήστε κενό για την προκαθορισμένη τιμή',
                               wrapper: {class: 'col-sm-6'} %>

            <%= f.text_field :comment, label: 'Σχόλιο' %>
            <%= f.form_group do %>
              <%= f.primary 'Ενημέρωση' %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products_services/edit_customer_service.html.erb
<div class="col-md-4 col-sm-4 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2 id="dd">Ενημέρωση Υπηρεσίας</h2>
      <h2 class="pull-right green sum">0€</h2>

      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <div class="panel-body">
        <%= bootstrap_form_tag url: {controller: 'products_services', action: 'update_customer_service'}, html: {id: 'add_product_service_form'} do |form| %>
          <%= form.fields_for @record, url: {controller: 'products_services', action: 'update_customer_service'} do |f| %>
            <%= f.select(:customer_id, @customers.pluck(:name, :id),
                         {label: 'Επιλέξτε Πελάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                         {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
            <%= f.select(:partner_id, @partners.pluck(:name, :id),
                         {label: 'Επιλέξτε Συνεργάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                         {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
            <%= f.select(:service_id, @records.collect {|p| [p, p.id, data: {'price': p.price}]},
                         {label: 'Επιλέξτε Υπηρεσία', :prompt => 'Δεν έχει επιλεγεί κάποια'},
                         {class: 'selectpicker in_price', 'data-live-search' => 'true'}) %>
            <%= datepicker_input(f, :created_at) %>

            <div class="col-sm-9">
              <%= f.select(:discount_id, @discounts.collect {|p| [p, p.id, data: {'percent': p.per_cent}]},
                           {label: 'Επιλέξτε Έκπτωση', :prompt => 'Δεν έχει επιλεγεί κάποια'},
                           {id: 'discount_id', class: 'selectpicker', 'data-live-search' => 'true'}) %>
            </div>

            <%= f.number_field :discount_per_cent, label: 'Έκπτωση',
                               id: 'discount_per_cent',
                               data: {toggle: 'tooltip'},
                               min: '0', max: '100',
                               wrapper: {class: 'col-sm-3'} %>

            <%= f.number_field :amount, label: 'Ποσότητα',
                               class: :amount,
                               data: {toggle: 'tooltip'},
                               title: 'αφήστε κενό για ποσότητα ίση με ένα',
                               wrapper: {class: 'col-sm-6'} %>

            <%= f.number_field :price, label: 'Τιμή',
                               class: 'text_field custom_price',
                               step: :any,
                               value: (@record.price * 100 / (100 - @record.discount_per_cent)).round(2),
                               data: {toggle: 'tooltip'},
                               title: 'αφήστε κενό για την προκαθορισμένη τιμή',
                               wrapper: {class: 'col-sm-6'} %>

            <%= f.text_field :comment, label: 'Σχόλιο' %>
            <%= f.form_group do %>
              <%= f.primary 'Ενημέρωση' %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>