config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :dashboard
  post 'dashboard' => 'dashboard#render_product_partial_form'

  resources :products_services

  delete 'customer_product/:id(.:format)' => 'products_services#destroy_customer_product', as: 'destroy_customer_product'
  delete 'customer_service/:id(.:format)' => 'products_services#destroy_customer_service', as: 'destroy_customer_service'

  get 'customer_product/:id(.:format)' => 'products_services#edit_customer_product', as: 'edit_customer_product'
  get 'customer_service/:id(.:format)' => 'products_services#edit_customer_service', as: 'edit_customer_service'

  post 'customer_product/:id(.:format)' => 'products_services#update_customer_product', as: 'update_customer_product'
  post 'customer_service/:id(.:format)' => 'products_services#update_customer_service', as: 'update_customer_service'

  resources :customers
  post 'customers/:id/' => 'customers#show_range', as: 'customer_range'

  resources :expenses

  resources :services do
    member do
      patch :toggle_enabled
    end
  end

  resources :products do
    member do
      patch :toggle_enabled
    end
  end

  resources :partners do
    member do
      patch :toggle_enabled
    end
  end

  resources :discounts do
    member do
      patch :toggle_enabled
    end
  end
  #path for charts
  get 'customer/products_services_by_day/:id/:range(.:format)' => 'customers#products_services_by_day', as: "customer_products_services_by_day"
  get 'dashboard_index/products_services_by_day' => 'dashboard#products_services_by_day', as: "dashboard_products_services_by_day"
  get 'dashboard_index/customers_by_sex' => 'dashboard#customers_by_sex', as: "dashboard_customers_by_sex"
  get 'dashboard_index/by_service' => 'dashboard#by_service', as: "dashboard_by_service"
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  belongs_to :user
  scope :by_user, ->(current_user) {where(user: current_user).order(name: :desc)}
  scope :by_user_no_order, ->(current_user) {where(user: current_user)}

  has_many :customer_products, :dependent => :restrict_with_error
  has_many :products, through: :customer_products, :dependent => :restrict_with_error

  has_many :customer_services, :dependent => :restrict_with_error
  has_many :services, through: :customer_services, :dependent => :restrict_with_error

  enum sex: [:woman, :man]

  def create_with_user(current_user)
    self.user = current_user if user.nil?
    save
  end

  def to_s
    "#{name}"
  end

  def sex_to_s
    woman? ? "Γυναίκα" : "'Ανδρας"
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @records = Customer.by_user(current_user)
  end

  def show
    @record = Customer.by_user(current_user).find(params[:id])
    @customer_services = @record.customer_services
    @customer_products = @record.customer_products
    tiles
  end

  def between_where(range)
    if range[:start] == ""
      {}
    else
      s = DateTime.strptime((range[:start].to_f / 1000).to_s, '%s')
      e = DateTime.strptime((range[:end].to_f / 1000).to_s, '%s')
      {:created_at => s..e}
    end

  end

  def show_range
    @record = Customer.by_user(current_user).find(params[:id])
    @range = {start: params[:start], end: params[:end], label: params[:label]}
    @customer_services = @record.customer_services.where(between_where(@range))
    @customer_products = @record.customer_products.where(between_where(@range))
    tiles
    render partial: 'customers/show_content'
  end

  def create
    @record = Customer.new(customer_params).create_with_user(current_user)
    redirect_to customers_path
  end

  def edit
    @records = Customer.by_user(current_user)
    @record = Customer.by_user(current_user).find(params[:id])
  end

  def update
    @record = Customer.by_user(current_user).find(params[:id])
    if @record.update_attributes(customer_params)
      redirect_to customers_path
    else
      render 'edit'
    end
  end

  def destroy
    @record = Customer.by_user(current_user).find(params[:id])
    @record.destroy
    redirect_to customers_path
  end


  def products_services_by_day
    @record = Customer.by_user(current_user).find(params[:id])

    @range = Rack::Utils.parse_nested_query(params[:range]).symbolize_keys
    print @range
    response = [
        {name: "Services", data: @record.customer_services.where(between_where(@range)).group_by_day(:created_at, format: "%B %d, %Y").count},
        {name: "Products", data: @record.customer_products.where(between_where(@range)).group_by_day(:created_at, format: "%B %d, %Y").count}
    ]
    render json: response
  end

  def customer_params
    params.require(:customer).permit(:name, :phone_1, :phone_2, :sex, :comment, :customer_range)
  end

  def tiles
    f = @record.customer_services.order(:created_at).first.created_at
    l = @record.customer_services.order(:created_at).last.created_at

    months_active = (l.year * 12 + l.month) - (f.year * 12 + f.month)

    visits = @record.customer_services.distinct.count(:created_at)
    av_visits = (visits.to_f / months_active.to_f).round(2)
    profit = (@record.customer_services.sum("price * amount") + @record.customer_services.sum("price * amount")).round(2)
    av_profit = (profit.to_f / months_active.to_f).round(2)
    services = @record.customer_services.count
    av_services = (services.to_f / months_active.to_f).round(2)
    products = @record.customer_products.count
    av_products = (products.to_f / months_active.to_f).round(2)
    prediction = predict_next_visit
    @tiles = {
        :months_active => months_active,
        :visits => visits,
        :av_visits => av_visits,
        :profit => profit,
        :av_profit => av_profit,
        :services => services,
        :av_services => av_services,
        :products => products,
        :av_products => av_products,
        :next_visit => prediction[:next_visit],
        :in_days => prediction[:in_days]
    }
  end

  def predict_next_visit2
    visits = @record.customer_services.distinct.order(created_at: :asc).pluck(:created_at)

    data = visits.each_with_index.map do |record, i|
      {visit: i, day_diff: (record - visits[0]).to_i / 1.day}
    end
    model = Eps::Model.new(data, target: :day_diff, algorithm: :linear_regression)
    actual = data[-1][:day_diff]
    prediction = model.predict(visit: data.length - 1)
    print actual
    print "\n"
    print prediction
    Eps.metrics(actual, prediction)


    print model.summary
    in_days = model.predict(visit: data.length).days
    next_visit = visits[0] + in_days
    {next_visit: visits[0] + in_days, in_days: (next_visit - Time.now).to_i / 1.day}
  end

  def predict_next_visit3
    visits = @record.customer_services.distinct.order(created_at: :asc).pluck(:created_at)
    y = visits.map do |record, i|
      ((record - visits[0]).to_i / 1.day)
    end
    x = []
    for i in 0..(y.length - 1)
      x.push([i])
    end
    print x
    print "\n"
    print y
    print "\n"
    linear_regression = RubyLinearRegression.new
    # Load training data
    linear_regression.load_training_data(x, y)
    # Train the model using the normal equation
    #linear_regression.train_normal_equation
    linear_regression.train_normal_equation

    p = x.map do |x_p|
      predicted = linear_regression.predict(x_p)
      predicted.round
    end
    print p
    print "\n"

    in_days = linear_regression.predict([y.length]).days
    next_visit = visits[0] + in_days
    {next_visit: visits[0] + in_days, in_days: (next_visit - Time.now).to_i / 1.day}
  end

  def predict_next_visit
    model = ML::Regress.new

    print model.regress([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        [1, 6, 17, 34, 57, 86, 121, 162, 209, 262, 321],
                        2)
    visits = @record.customer_services.distinct.order(created_at: :asc).pluck(:created_at)

    y = visits.map do |record, i|
      ((record - visits[0]).to_i / 1.day)
    end
    y = y.uniq
    x = []
    for i in 0..(y.length - 1)
      x.push(i)
    end
    print x
    print "\n"
    print y
    print "\n"
    # Load training data
    model.regress(x, y, 2)

    p = x.map do |x_p|
      predicted = model.predict(x_p)
      predicted.round
    end
    print p
    print "\n"

    in_days = model.predict(y.length).days
    next_visit = visits[0] + in_days
    {next_visit: visits[0] + in_days, in_days: (next_visit - Time.now).to_i / 1.day}
  end


end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_chart_test.erb
<% unless @range %>
  <% @range = {label: "All", start: "", end: ""} %>
<% end %>
<div class="col-md-6 col-sm-6 col-xs-12 ">
  <%= line_chart customer_products_services_by_day_url(@record.id, @range.to_query), discrete: true %>
</div>

app/views/customers/_create_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Δημιουργία Πελάτη</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <%= bootstrap_form_for :customer, url: {controller: 'customers', action: 'create'} do |f| %>
      <%= f.text_field :name, label: 'Όνομα' %>
      <%= f.select :sex, [['Γυναίκα', :woman], ['Άνδρας', :man]], {label: 'Επιλέξτε φύλο:'}, {class: 'selectpicker'} %>
      <%= f.phone_field :phone_1, label: 'Τηλέφωνο 1' %>
      <%= f.phone_field :phone_2, label: 'Τηλέφωνο 2' %>
      <%= f.text_field :comment, label: 'Σχόλιο' %>
      <%= f.form_group do %>
        <%= f.primary 'Δημιουργία' %>
      <% end %>
    <% end %>
  </div>
</div>

<script>
    $('.selectpicker').selectpicker();
</script>

app/views/customers/_customer_tiles.html.erb
<!-- top tiles -->
<div class="tile_count col-md-12 " id="tiles" style="display: none;">
  <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-user"></i> Επισκέψεις - Μήνες</span>
    <div class="count blue"><%= @tiles[:visits].to_s + " - " + @tiles[:months_active].to_s %></div>
    <span class="count_bottom"><i class="green"><%= @tiles[:av_visits] %> </i> μ.ο. επισκέψεων ανά μήνα</span>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-scissors"></i> Συνολικό κέρδος</span>
    <div class="count pink"><%= @tiles[:profit] %></div>
    <%= regular_tile(@tiles[:av_profit], 'μ.ο. ανά μήνα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-ice-lolly"></i> Συνολικές Υπηρεσίες</span>
    <div class="count pink"><%= @tiles[:services] %></div>
    <%= regular_tile(@tiles[:av_services], 'μ.ο. ανά μήνα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-ice-lolly"></i> Συνολικά Προϊόντα</span>
    <div class="count pink"><%= @tiles[:products] %></div>
    <%= regular_tile(@tiles[:av_products], 'μ.ο. ανά μήνα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-ice-lolly"></i> Πρόβλεψη</span>
    <div class="count pink"><%= @tiles[:next_visit] %></div>
    <%= regular_tile(@tiles[:in_days], 'επομένη επίσκεψη') %>
  </div>
</div>
<!-- /top tiles -->

app/views/customers/_edit_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Ενημέρωση Πελάτη</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <%= bootstrap_form_for @record, url: {controller: 'customers', action: 'update'} do |f| %>
      <%= f.text_field :name, label: 'Όνομα' %>
      <%= f.select :sex, [['Γυναίκα', :woman], ['Άνδρας', :man]], {label: 'Επιλέξτε φύλο:'}, {class: 'selectpicker'} %>
      <%= f.phone_field :phone_1, label: 'Τηλέφωνο 1' %>
      <%= f.phone_field :phone_2, label: 'Τηλέφωνο 2' %>
      <%= f.text_field :comment, label: 'Σχόλιο' %>
      <%= f.form_group do %>
        <%= f.primary 'Ενημέρωση' %>
      <% end %>
    <% end %>
  </div>
</div>
<script>
    $('.selectpicker').selectpicker();
</script>

app/views/customers/_show_content.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "customers.js", 'data-turbolinks-track' => true %>
<% end %>


<%= render 'customers/chart_test' %>

<div class="col-md-6 col-sm-6 col-xs-12 pull-right">
  <%= render 'customers/table_services' %>
</div>
<div class="col-md-6 col-sm-6 col-xs-12 pull-right">
  <%= render 'customers/table_products' %>
</div>

app/views/customers/_table.erb
<div class="x_panel">
  <div class="x_content">
    <table id="datatable-customers" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>Όνομα</th>
        <th>Φύλο</th>
        <th>Τηλέφωνο 1</th>
        <th>Τηλέφωνο 2</th>
        <th>Σχόλιο</th>
        <th>Ενημέρωση</th>
        <th>Διαγραφή</th>
      </tr>
      </thead>
      <tbody>
      <% @records.each {|record| %>
        <tr>
          <%= show_row(record, record.name) %>
          <%= row(record.sex_to_s) %>
          <%= row(record.phone_1) %>
          <%= row(record.phone_2) %>
          <%= row(record.comment) %>
          <%= edit_row(edit_customer_path(record)) %>
          <%= delete_row(record) %>
        </tr>
      <% } %>
      </tbody>
    </table>
  </div>
</div>

<script>
    $('#datatable-customers').DataTable({
        "columnDefs": [
            {"width": "50px", "targets": [5, 6], "orderable": false, "className": "text-center"}
        ],
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Greek.json"
        }
    });
</script>

app/views/customers/_table_products.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Προϊόντα</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table id="datatable-customer_products_by_customer" class="table table-bordered" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>Προϊόν</th>
        <th>Ποσότητα - Τιμή</th>
        <th>Σχόλιο</th>
        <th>Ημ/Ώρα</th>
        <th>Διαγραφή</th>
      </tr>
      </thead>
      <tbody>
      <% @customer_products.each { |record| %>
        <tr>
          <%= row(record.product.to_s_name_description) %>
          <%= row_with_tooltip(record.amount_price,
                               record.price_tooltip,
                               "data-sort='#{record.total_paid}'") %>
          <%= row(record.comment) %>
          <%= row_with_tooltip(record.created_at_s,
                               time_ago_in_words(record.created_at),
                               "data-sort='#{record.created_at}'") %>
          <%= delete_row(destroy_customer_product_path(record)) %>
        </tr>
      <% } %>
      </tbody>
    </table>
  </div>
</div>

app/views/customers/_table_services.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Υπηρεσίες</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table id="datatable-customer_services_by_customer" class="table table-bordered" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>Υπηρεσία</th>
        <th>Συνεργάτης</th>
        <th>Ποσότητα - Τιμή</th>
        <th>Σχόλιο</th>
        <th>Ημ/Ώρα</th>
        <th>Διαγραφή</th>

      </tr>
      </thead>
      <tbody>

      <% @customer_services.each { |record| %>
        <tr>
          <%= row(record.service.to_s_name_description) %>
          <%= row(record.partner.to_s) %>
          <%= row_with_tooltip(record.amount_price,
                               record.price_tooltip,
                               "data-sort='#{record.total_paid}'") %>
          <%= row(record.comment) %>
          <%= row_with_tooltip(record.created_at_s,
                               time_ago_in_words(record.created_at),
                               "data-sort='#{record.created_at}'") %>
          <%= delete_row(destroy_customer_service_path(record)) %>

        </tr>
      <% } %>
      </tbody>
    </table>
  </div>
</div>

app/views/customers/_tiles.html.erb
<div class="col-md-6 col-sm-6 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Line graph
        <small>Sessions</small>
      </h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a>
            </li>
            <li><a href="#">Settings 2</a>
            </li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <canvas id="lineChart"></canvas>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<div class="col-md-8 col-sm-8 col-xs-12">
  <%= render 'customers/table' %>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
  <%= render 'customers/edit_form' %>
</div>

app/views/customers/index.html.erb
<div class="col-md-8 col-sm-8 col-xs-12">
  <%= render 'customers/table' %>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
  <%= render 'customers/create_form' %>
</div>

app/views/customers/show.html.erb
<%= render 'customers/customer_tiles' %>

<ul class="nav navbar-nav navbar-right" style="margin-bottom: 5px;">
  <%= bootstrap_form_tag url: dashboard_index_path, html: {id: 'add_product_service_form'} do |f| %>
    <%= f.text_field :date_range, data: {provide: 'datepicker'}, class: 'date_range', label: "Εύρος αναζήτησης" %>
  <% end %>
</ul>
<div id="show_content">
  <%= render 'customers/show_content' %>
</div>